
server:
  port: 8080
  servlet:
    context-path: /mybatis

spring:
  application:
    name: mybatis
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-actual-param-name: false
    default-executor-type: simple
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
  mapper-locations: com.footprint.mybatis.mapper.*
logging:
  level.com.footprint.mybatis: debug



